cms_category:
    path:     /
    defaults: { _controller: "CustomcmsBundle:Category:index" }

cms_category_show:
    path:     /{id}/show
    defaults: { _controller: "CustomcmsBundle:Category:show" }

cms_category_new:
    path:     /new
    defaults: { _controller: "CustomcmsBundle:Category:new" }

cms_category_create:
    path:     /create
    defaults: { _controller: "CustomcmsBundle:Category:create" }
    requirements: { _method: post }

cms_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "CustomcmsBundle:Category:edit" }

cms_category_update:
    path:     /{id}/update
    defaults: { _controller: "CustomcmsBundle:Category:update" }
    requirements: { _method: post|put }

cms_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "CustomcmsBundle:Category:delete" }
    requirements: { _method: post|delete }
